name = "MagiTechHeaven"
author = "EuSoJao"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01a439ff655a5cc8cbca3ce97d8b0a97b94d7f71a9105bc8b25e406794229d1b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
