name = "MagiTechHeaven"
author = "EuSoJao"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a2a9997ac7c2f9c8c49ed596ce0784074ff203a1714ab48c325a9661e401b4b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
