name = "MagiTechHeaven"
author = "EuSoJao"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2f2249104c0e920c2c99c1c68a23dea31e82c013a578b156e25bf9e46fb66ea"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
