name = "MagiTechHeaven"
author = "EuSoJao"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2062df0a02805afb5a0a14494768ed45c4eacb1bd572ca61df26d4186cd6b0e3"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
