name = "MagiTechHeaven"
author = "EuSoJao"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d1c3f907d4f215441f7654332b2f1d1bc9cbcd443c26bf9a9254dea677171d2"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
