name = "MagiTechHeaven"
author = "EuSoJao"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b4e03cc19d15d83cb5b7b6caf3d58ed1f3655b27393063a81d00dc03b51c283"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
