name = "MagiTechHeaven"
author = "EuSoJao"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "207fbbad67dec54257b425a20d62f892bcaa9e95d521c7ca609f6882defa2334"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
